// Generated by CoffeeScript 1.9.3
(function() {
  var expect, mockPath, mockWithImportPath, mockWithNpmImportPath;

  expect = require('chai').expect;

  global.injector = require('../index');

  mockPath = require.resolve('./mocks/mathModule');

  mockWithImportPath = require.resolve('./mocks/mathModuleWithImport');

  mockWithNpmImportPath = require.resolve('./mocks/mathModuleWithNpmImport');

  describe('commonjs-injector Module', function() {
    describe('When bypassInjection is set to true (default)', function() {
      beforeEach(function() {
        return injector.bypassInjection(true);
      });
      it('should let you export a module as a regular node.js module', function() {
        var mathModule;
        mathModule = require(mockPath);
        expect(mathModule).to.be.an('object');
        expect(mathModule.square(5)).to.equal(25);
        return delete require.cache[mockPath];
      });
      it('should let you use @import inside the injector fn to require regular modules', function() {
        var mathModule;
        mathModule = require(mockWithImportPath);
        expect(mathModule.pi).to.equal(Math.PI);
        return delete require.cache[mockWithImportPath];
      });
      return it('should let you use @import inside the injector fn to require npm modules', function() {
        var mathModule;
        mathModule = require(mockWithNpmImportPath);
        expect(mathModule.pi).to.equal(Math.PI);
        return delete require.cache[mockWithNpmImportPath];
      });
    });
    return describe('When bypassInjection is set to false', function() {
      beforeEach(function() {
        return injector.bypassInjection(false);
      });
      it('should let you export a fn wrapper that accepts an object with dependencies and returns the module when called', function() {
        var mathModule, mathModuleWrapper;
        mathModuleWrapper = require(mockPath);
        expect(mathModuleWrapper).to.be.an('function');
        mathModule = mathModuleWrapper();
        expect(mathModule).to.be.an('object');
        return delete require.cache[mockPath];
      });
      it('should let you export a fn wrapper that accepts an object with dependencies and uses @import internally', function() {
        var mathModule, mathModuleWrapper;
        mathModuleWrapper = require(mockWithImportPath);
        expect(mathModuleWrapper).to.be.an('function');
        mathModule = mathModuleWrapper();
        expect(mathModule).to.be.an('object');
        expect(mathModule.pi).to.equal(Math.PI);
        return delete require.cache[mockWithImportPath];
      });
      return it('should let you inject dependencies that are required internally via @import', function() {
        var mathModule, mathModuleWrapper;
        mathModuleWrapper = require(mockWithImportPath);
        mathModule = mathModuleWrapper({
          'PiModule': 'Mocked PI Value'
        });
        expect(mathModule).to.be.an('object');
        expect(mathModule.pi).to.equal('Mocked PI Value');
        return delete require.cache[mockWithImportPath];
      });
    });
  });

}).call(this);

//# sourceMappingURL=index.spec.js.map
