// Generated by CoffeeScript 1.11.1
(function() {
  injector.set(function() {
    return Math.PI;
  });

  module.exports = injector.get();

}).call(this);

//# sourceMappingURL=injectorPiModule.js.map
