// Generated by CoffeeScript 1.9.3
(function() {
  injector.set(function(dependencies) {
    this.dependencies = dependencies;
    return Math.PI;
  });

  module.exports = injector.get();

}).call(this);

//# sourceMappingURL=injectorPiModule.js.map
