// Generated by CoffeeScript 1.9.3
(function() {
  injector.set(function(dependencies) {
    var math;
    this.dependencies = dependencies;
    math = {
      square: function(x) {
        return x * x;
      }
    };
    return math;
  });

  module.exports = injector.get();

}).call(this);

//# sourceMappingURL=mathModule.js.map
