// Generated by CoffeeScript 1.11.1
(function() {
  injector.set(function() {
    var math;
    math = {
      square: function(x) {
        return x * x;
      }
    };
    return math;
  });

  module.exports = injector.get();

}).call(this);

//# sourceMappingURL=mathModule.js.map
